### ISSUE TITLE
Problems migrating to kubernetes with POSTGRES_USERNAME and POSTGRES_PASSWORD

### ISSUE THREAD

**Issue by logronoide** [DanielDent/docker-postgres-replication#3]
I'm migrating the docker-compose.yml to kubernetes, but I'm facing an issue that it seems to me has nothing to do with k8s, but with postgres, and I'm not an expert in postgres.

I got the following error when connecting a slave to a successfully  deployed (and functional) master:

```
2016-10-26T10:39:48.274183765Z pg_basebackup: could not connect to server: FATAL:  role "-vP" does not exist
2016-10-26T10:39:48.274942692Z Waiting for master to connect...
```

The message repeats endlessly because it's inside a until/done structure.

The k8s pod file below:

```
apiVersion: v1
kind: Pod
metadata:
  name: postgres-slave
  labels:
    name: postgres-slave
spec:
  containers:
    - name: postgres-slave
      image: danieldent/postgres-replication:9.6
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: REPLICATE_FROM
          value: "10.1.5.4"
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data-slave
  volumes:
    - name: pg-data-slave
      emptyDir: {}
```

The container pings successfully to the master in 10.1.5.4 (I know I should connect to a service name, but this is a test), but afterwards I got the error above.

Now, if I change POSTGRES_USER and POSTGRES_PASSWORD to the deprecated version (PGUSER and PGPASSWORD), then the container passes the endless loop and replicates from the master correctly.
